### ISSUE TITLE
Not compatible with Django 3.0

### ISSUE THREAD

**Issue by matthijskooijman** [lukeburden/django-constants#10]
In Django 3.0, the `python_2_unicode_compatible` helper is removed, which breaks django-konst.

This could be fixed by:
 - Dropping support for python2
 - When not available in Django, define the helper function as a no-op (as it was when using Python3 already).

I would suggest doing the former, since Django has dropped support for Python2 in Django 2.0 two years ago already.

**Comment by matthijskooijman** [comment]
Seems this is fixed by #11? Haven't tested yet, though, my application isn't ported to Django3 yet.

**Comment by lukeburden** [comment]
Heya @matthijskooijman - yep, this lib is now Django 3.X compatible.
