### ISSUE TITLE
Suggestion: Let ConstantChoiceFieldMixin.to_python handle strings too

### ISSUE THREAD

**Issue by matthijskooijman** [lukeburden/django-constants#14]
I tried to import a fixture (using `./manage.py loaddata` that contained a string for a Constant field (which seemed like the right way to do this), but that failed with:
```
Traceback (most recent call last):
  File "/data/www/evolution-events.nl/applications/Artaxerxes/venv/lib/python3.7/site-packages/django/core/serializers/python.py", line 143, in Deserializer  
    data[field.name] = field.to_python(field_value)
  File "/data/www/evolution-events.nl/applications/Artaxerxes/venv/lib/python3.7/site-packages/konst/models/fields.py", line 22, in to_python                 
    return self.constants.by_value.get(int(value))
ValueError: invalid literal for int() with base 10: 'REGISTERED' 
```

(the trace up to there for django's deserialization is hidden).

If `to_python` would check for a string argument and handle that appropriately like (`ConstantChoiceCharField` already does), then I think deserializing a constant from its name would be possible.

To also serialize to such values, I think `value_to_string` should return the string value of a constant as well: https://docs.djangoproject.com/en/3.0/ref/models/fields/#django.db.models.Field.value_to_string

For backward compatibility, I guess `to_python` should continue to fall back to parsing an integer from the string if it does not match any constant name.

**Comment by lukeburden** [comment]
Heya @matthijskooijman - I'm open to this if you want to experiment in a PR.
