### ISSUE TITLE
Suggestion: Allow assigning `field.CONSTANT` as well

### ISSUE THREAD

**Issue by matthijskooijman** [lukeburden/django-constants#15]
You can currently say:

    print(apple.colour.green)

But not:

    apple.color.green = True

I somwhat expected the latter to work, but instead it just silently assigns the `green` attribute on the (I think) `Constant` object instead.

It would be nice if this would work, since it makes getting and setting these constants nicely mirrored. 

I'm not quite sure if this is possible (you can overload e.g. `apple.color.__set_attr__()` you'd get mutable Constant objects, which are probably going to byte you. You'd *want* to rebind `apple.color`, but I'm not sure if you have enough context for that. If this is indeed impossible, it might at least be useful to make `Constant.__set_attr__` raise an exception.

**Comment by lukeburden** [comment]
I am conscious that setting is a bit clunky at the moment, but the current approach does have the advantage of simplicity with little magic. Your suggestion feels a little magic to me (if I'm setting something to True, I'd expect it to have that actual concrete value) and I'm also not sure how feasible it is technically.

If you feel strongly about this, we can discuss further, but for now I'd suggest just setting using the somewhat-clunky-but-simple:

`apple.color = Apple.colors.green`
