### ISSUE TITLE
RFC: What is needed for a 1.0 release

### ISSUE THREAD

**Issue by lukeburden** [lukeburden/django-constants#3]
To anyone out there who sees this and thinks this utility may be of use to them! I'm working toward a 1.0 release, and it'd be invaluable for me to get your feedback prior to needing to enforce backward compatibility, etc.

Concerns, requests, general feedback - all welcome.

@paltman, bring your friends. :)

**Comment by paltman** [comment]
Sorry I never got back to you. Been swamped.

**Comment by lukeburden** [comment]
No problem at all - I'm releasing 1.0 as I want to cut the original code out of our projects and use this library as a proper dependency.

I'd love to hear your thoughts if you ever find this little utility useful.
