### ISSUE TITLE
Suggestion: Improving query filters with custom lookups?

### ISSUE THREAD

**Issue by matthijskooijman** [lukeburden/django-constants#9]
Currently, to do a query filter on a ConstChoiceField, you use e.g.:

    eating_apples = Apple.objects.filter(purpose=Apple.purposes.eating)
    culinary_apples = Apple.objects.filter(purpose__in=Apple.purposes.culinary)

This seems more verbose than ideal. Explicitly specifying `Apple.purposes` should not be needed, since that should be clear from the context already. Ideally, you'd write:

    eating_apples = Apple.objects.filter(purpose=eating)

But that's not something supported by Python (it would need context-dependent name lookup, I think). Another alternative would be:

    eating_apples = Apple.objects.filter(purpose='eating')

Which is a bit less nice because it uses a string, but would certainly be an improvement (especially if this would raise an exception when you misspell the string).

Another approach to consider would be more in line with the normal attribute lookups (e.g. `if apple.purpose.eating`) is:

    eating_apples = Apple.objects.filter(purpose__eating=True)

Both of the latter two are valid python and need some Django machinery to work. I'm pretty sure the latter can be made to work using custom field lookups (e.g. `__eating` is a lookup in django terms). Probably the former as well, by overriding the default `__exact` lookup (I think `purpose='eating'` is internally treated as `purpose__exact='eating'`).

See https://docs.djangoproject.com/en/2.2/ref/models/lookups/ and https://docs.djangoproject.com/en/2.2/howto/custom-lookups/

If I can find some time, I might have a look at implementing this, but wanted to at least share the idea already and maybe get some feedback.

**Comment by lukeburden** [comment]
Thanks for your detailed thoughts here @matthijskooijman. I kinda like your last suggestion:

`eating_apples = Apple.objects.filter(purpose__eating=True)`

As it is somewhat similar to `__is_null=True`, and other ORM constructs. But personally, I'm a fan of the somewhat verbose but simple:

`eating_apples = Apple.objects.filter(purpose=Apple.purposes.eating)`

I'm open to a PR if you want to experiment with the custom lookup, though.

**Comment by lukeburden** [comment]
I do like this idea, but since it is just syntactic improvement and no PR is forthcoming, I'll close this for now.

**Comment by matthijskooijman** [comment]
Yeah, I understand, and apologies for not responding earlier. Making a PR is still on my TODO-list somewhere, and I might get around to it someday, but other things will likely have more priority. In any case, if I do find some time, I'll find these issues even when they're closed :-)
